### ISSUE TITLE
Create refresh token programatically

### ISSUE THREAD

**Issue by noook** [markitosgv/JWTRefreshTokenBundle#152]
It it possible to fetch the refresh token programmatically ? I mean, creating the new one on login

**Comment by AntoineGriffon** [comment]
You can create a refresh token programmatically by using the RefreshTokenManager, you just have to inject RefreshTokenManagerInterface an use the following code:

`
final class SomeService {
public function __construct(RefreshTokenManagerInterface $refreshTokenManager)
    {
        $this->refreshTokenManager = $refreshTokenManager;
    }

public function create(): RefreshTokenManagerInterface
{
$valid = new DateTime('now');
$valid->add(new DateInterval('P3D'));
$refreshToken = $this->refreshTokenManager->create();
$refreshToken->setUsername($user->getUsername());
$refreshToken->setRefreshToken();
$refreshToken->setValid($valid);
$this->refreshTokenManager->save($refreshToken);
}
}`
