### ISSUE TITLE
Add support to doctrine/mongodb-odm-bundle 4.x

### ISSUE THREAD

**Issue by lcavero** [markitosgv/JWTRefreshTokenBundle#168]
Hi, I get the following exception when I update doctrine/mongodb-odm-bundle from 3.x to 4.x

!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "createYamlMappingDriver" of class "Doctrine\Bundle\MongoDBBundle\DependencyInjection\Compiler\DoctrineMongoDBMappingsPass".
!!  Did you mean to call e.g. "createPhpMappingDriver" or "createXmlMappingDriver"? in /xxx/vendor/gesdinet/jwt-refresh-token-bundle/DependencyInjection/Compiler/DoctrineMappingsCompilerPass.php:93

Could you add support? thanks

**Comment by juliangut** [comment]
Next versions of Doctrine's ORM and ODM are dropping yaml support, and so they seem to be preparing the bundles (https://github.com/doctrine/DoctrineMongoDBBundle/pull/475)

**Comment by markitosgv** [comment]
Resolved #167
