### ISSUE TITLE
Refresh token now requires non plural table name

### ISSUE THREAD

**Issue by jeystaats** [markitosgv/JWTRefreshTokenBundle#170]
We've updated the current version of this library today to 8.0, the problem is that it suddenly requires the table
```
refresh_token
```
instead of the previous plural version
```
refresh_tokens
```

What causes this sudden change and how can we prevent it to select the non plural version of the table name? On 7.1 we didn't have this problem.

I assume it is because RefreshToken.orm.xml doesn't have a table name specified since 0.8.0 therefore it chooses the default name for a table based on the EntityRepository.

Thanks!

**Comment by samikroon** [comment]
Same problem. Also wondering why all the configs changed form yaml to xml.

**Comment by markitosgv** [comment]
Hi @jeystaats ,

We remove 0.8 release, cause it fails beacause a mapping error in xml.

@samikroon, we moved to xml mapping because odm 2.0 release

**Comment by markitosgv** [comment]
Working on #169

**Comment by jeystaats** [comment]
Cheers! Thanks for the fast response and fix
