### ISSUE TITLE
Wrong type mapping for valid field.

### ISSUE THREAD

**Issue by Japonics** [markitosgv/JWTRefreshTokenBundle#172]
In XML entity definition (version 0.8.1) `valid` field is mapped as `date`, but previous version
type definition was `datetime`. Due to this change it is thrown parse exception:

`Could not convert database value \"2019-11-13 00:00:00\" to Doctrine Type date. Expected format: Y-m-d`.

Definition file: Resources/config/orm/doctrine-entity/RefreshToken.orm.xml 

The same situation is for mongo document definition.

**Comment by markitosgv** [comment]
Ok thanks, solved in release 0.8.2
