### ISSUE TITLE
Doctrine\ORM\EntityManager required

### ISSUE THREAD

**Issue by vanherst** [markitosgv/JWTRefreshTokenBundle#205]
I get the following exception on a Symfony 4.4 project after following the installation guide.

Uncaught Error: Argument 1 passed to Gesdinet\JWTRefreshTokenBundle\Doctrine\RefreshTokenManager::__construct() must be an instance of Doctrine\Common\Persistence\ObjectManager, instance of Doctrine\ORM\EntityManager given, called in \var\cache\dev\ContainerQVHpDrM\srcApp_KernelDevDebugContainer.php

Is this a bug or have I made a mistake?

**Comment by SiM07** [comment]
See https://github.com/markitosgv/JWTRefreshTokenBundle/issues/200
