### ISSUE TITLE
After update from SF5.0 to 5.1 problem with RefreshTokenManager

### ISSUE THREAD

**Issue by jarekkowol** [markitosgv/JWTRefreshTokenBundle#218]
After symfony update, i get this error: 

`Argument 1 passed to Gesdinet\\JWTRefreshTokenBundle\\Doctrine\\RefreshTokenManager::__construct() must be an instance of Doctrine\\Common\\Persistence\\ObjectManager, instance of ContainerSBxRwEn\\EntityManager_9a5be93 given, called in \/Users\/jaroslawkowol\/PhpstormProjects\/sarelite-main\/var\/cache\/dev\/ContainerSBxRwEn\/App_KernelDevDebugContainer.php on line 2806`

Who will help?

**Comment by fd6130** [comment]
Clear your cache?

**Comment by crashkita** [comment]
I have a same error: 
`Argument 1 passed to Gesdinet\JWTRefreshTokenBundle\Doctrine\RefreshTokenManager::__construct() must be an instance of Doctrine\Common\Persistence\ObjectManager, instance of Doctrine\ORM\EntityManager given`

**Comment by fd6130** [comment]
Have a look at #200

**Comment by ganeshbala2008** [comment]
@jarekkowol 
The error is due to the custom user provider is set NULL. we can solve it,
By running the below command you will get the concrete class of your custom user provider.
`php bin/console debug:container`

Then add it on the configuration of gesdinet refresh token
```
gesdinet_jwt_refresh_token:
  user_provider: security.user.provider.concrete.app_user_provider

```

**Comment by fd6130** [comment]
You may refer to **Config UserProvider** section in docs.

**Comment by maxhelias** [comment]
Fixed by https://github.com/markitosgv/JWTRefreshTokenBundle/pull/213
