### ISSUE TITLE
support symfony 5.2 and php 8

### ISSUE THREAD

**Issue by iamfarhad** [markitosgv/JWTRefreshTokenBundle#219]

**Comment by informatic-revolution** [comment]
Hi, do you plan to add php 8 support ?

**Comment by lexdevelop** [comment]
Any update on this?

**Comment by fd6130** [comment]
I think Symfony 5.2 already supported? Not sure about php 8 though.

**Comment by informatic-revolution** [comment]
It is compatible with symfomy 5.2 and php 8.
