### ISSUE TITLE
Doctrine ORM and ODM support

### ISSUE THREAD

**Issue by piotrkreft** [markitosgv/JWTRefreshTokenBundle#228]
Hi,
currently, bundle implementation is based on Doctrine Persistence interfaces i.e. `Doctrine\Persistence\ObjectManager`. It does not strictly depend on having ORM or ODM installed - this is being resolved dynamically.
However, enforcing one of those might be a bit of a pain as many applications may not require any of them but still in need of JWT implementation and refreshing of it.
As far I see the only place which actually enforces having ORM/ODM is `Gesdinet\JWTRefreshTokenBundle\DependencyInjection\Compiler\DoctrineMappingsCompilerPass` - it resolves the manager based on the fact of having installed certain classes. In the case of ORM, it is DoctrineBundle which might be installed but you still could have ORM not enabled via configuration.

I work with an application that actually uses DBAL and DoctrineBundle configuration for it but not ORM(nor ODM). Currently, it is hacked to disable mapping via a separate compiler pass manipulating configuration and just having its own way simpler logic implementing Doctrine Persistence for RefreshToken entity.

Would you consider extending the bundle configuration with the option to disable those mapping in the compiler pass? If yes I'd be happy to try and propose a PR for it.

**Comment by markitosgv** [comment]
Hi @piotrkreft , this is a good feature , of course you could propose a PR

**Comment by piotrkreft** [comment]
PR #229 merged and released
