### ISSUE TITLE
Invalid new php configuration

### ISSUE THREAD

**Issue by piotrkreft** [markitosgv/JWTRefreshTokenBundle#232]
The new configuration introduced in version 0.11.0 (PR #223) contains some issues with injecting string values instead of parameters, invalid service definition instead of alias etc.

It seems like PR #224 rollbacks the changes to the appropriate state already so worth checking out.

version: 0.11.0
file: Resources/config/services.php

**Comment by markitosgv** [comment]
Released a new v0.11.1 could you try it?

**Comment by piotrkreft** [comment]
Now it seems to be work back again. Thanks for the vast response!
