### ISSUE TITLE
Symfony 5.x support?

### ISSUE THREAD

**Issue by tlorens** [markitosgv/JWTRefreshTokenBundle#238]
Symfony continues to move at a steady pace.  I see ^5.0 in the composer.json, ^5.2 would be closer to where things stand today.

**Comment by fd6130** [comment]
Isn't that ^5.0 mean 5.1, 5.2 ... and so on are acceptable?

**Comment by tlorens** [comment]
You'd think, since that equates to something like ">=5.0.0 <6.0.0-0.".  but for some odd reason composer is complaining.

**Comment by lyrixx** [comment]
It works well with SF 5.2 (we use it in production)
And I made a PR (already merged / released)  to make it compatible with SF 5.3
SO IMHO, there is nothing to do here

**Comment by markitosgv** [comment]
It works with Symfony 5
