### ISSUE TITLE
Symfony 6 - dependency problem

### ISSUE THREAD

**Issue by ajay-gupta** [markitosgv/JWTRefreshTokenBundle#297]
The latest release 1.0 is showing problem in Symfony 6.0 dependency.

`gesdinet/jwt-refresh-token-bundle v1.0.0 requires symfony/deprecation-contracts ^2.1 -> found symfony/deprecation-contracts[v2.1.0, ..., v2.5.0] but the package is fixed to v3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.`

![image](https://user-images.githubusercontent.com/7347112/149952733-46a15f60-ab3d-4a18-87d9-0c99df300358.png)

**Comment by gatmanmihai** [comment]
Any chance the PR will be merged soon ?

**Comment by webignition** [comment]
That's a little odd. I'm using `"gesdinet/jwt-refresh-token-bundle": "dev-master#e963f736079214627afb2a0c36386ccd0b56338a"` in a SF 6.0 app without issue.

What in your project requires `symfony/deprecation-contracts` version `3.0` specifically? 

If you specify the `-W` flag as composer suggests, are you able to successfully downgrade `symfony/deprecation-contracts` to `^2.1`?

**Comment by ajay-gupta** [comment]
I  have checked the `symfony/deprecation-contracts` to identify the package.

Most of the packages are supporting both the versions.  The package `easycorp/easyadmin-bundle` has removed the `^2.1` support.

We can add 3.0 as most of the Symfony packages are supporting both.

![image](https://user-images.githubusercontent.com/7347112/150514494-6ae37804-4882-433b-952b-55ed1f3d670c.png)

**Comment by emokykla** [comment]
> That's a little odd. I'm using `"gesdinet/jwt-refresh-token-bundle": "dev-master#e963f736079214627afb2a0c36386ccd0b56338a"` in a SF 6.0 app without issue.
> 
> What in your project requires `symfony/deprecation-contracts` version `3.0` specifically?
> 
> If you specify the `-W` flag as composer suggests, are you able to successfully downgrade `symfony/deprecation-contracts` to `^2.1`?

how do you using ? because when i try your `composer require "gesdinet/jwt-refresh-token-bundle":"dev-master#e963f736079214627afb2a0c36386ccd0b56338a"` I got same error like I would use just `composer require gesdinet/jwt-refresh-token-bundle`. New sf6.0 app.

**Comment by scorpioniz** [comment]
> That's a little odd. I'm using `"gesdinet/jwt-refresh-token-bundle": "dev-master#e963f736079214627afb2a0c36386ccd0b56338a"` in a SF 6.0 app without issue.
> 
> What in your project requires `symfony/deprecation-contracts` version `3.0` specifically?
> 
> If you specify the `-W` flag as composer suggests, are you able to successfully downgrade `symfony/deprecation-contracts` to `^2.1`?

how do you using ? because when i try your `composer require "gesdinet/jwt-refresh-token-bundle":"dev-master#e963f736079214627afb2a0c36386ccd0b56338a"` I got same error like I would use just `composer require gesdinet/jwt-refresh-token-bundle`. New sf6.0 app.

**Comment by webignition** [comment]
@scorpioniz I guess you have a dependency (direct or otherwise) that conflicts with what this package currently depends on and that I don't. If you're encountering the same issue as @ajay-gupta then this will certainly be the case. If not, hard to say without further details about the dependency resolution issues you're seeing.

**Comment by scorpioniz** [comment]
@webignition yep :) I have this dependency directly. Seems I will need to wait while PR will be merged. ;(
