### ISSUE TITLE
Table `refresh_tokens` no longer generated in test environment

### ISSUE THREAD

**Issue by Jayfrown** [markitosgv/JWTRefreshTokenBundle#314]
After updating to `v1.1.1` (and consolidating the firewall configurations) the `refresh_tokens` table is no longer automatically generated in my test environment. It works as expected in the `dev` environment.

I have some integration tests that hit the refresh endpoint and expect certain responses, which now complains as follows:

```
1) App\Tests\Integration\AuthenticationTest::testTokenEndpointsWorkAsExpected
Failed asserting that the Response is successful.
HTTP/1.1 500 Internal Server Error

{
  "@context":"\/api\/contexts\/Error",
  "@type":"hydra:Error",
  "hydra:title":"An error occurred",
  "hydra:description":"An exception occurred while executing a query: Table 'app_test.refresh_tokens' doesn't exist"
  [..]
```

**Comment by darthf1** [comment]
I had the same; did you create the entity as I. Step 3 of the readme?

**Comment by Jayfrown** [comment]
Thanks @darthf1, I didn't realize this is now required.
