### ISSUE TITLE
"message":"Repository mapped for \"App\\Entity\\JwtRefreshToken\" should implement Gesdinet\\JWTRefreshTokenBundle\\Doctrine\\RefreshTokenRepositoryInterface."

### ISSUE THREAD

**Issue by groupemyconnecting** [markitosgv/JWTRefreshTokenBundle#341]
Hello i have this message after upgrade the bundle JWTRefreshToken to 1.1.1 
I have this message
"message":"Repository mapped for \"App\\Entity\\JwtRefreshToken\" should implement Gesdinet\\JWTRefreshTokenBundle\\Doctrine\\RefreshTokenRepositoryInterface."

My class: 
`
use App\Repository\JwtRefreshTokenRepository;
use Doctrine\ORM\Mapping as ORM;
use Gesdinet\JWTRefreshTokenBundle\Model\AbstractRefreshToken;

/**
 * @ORM\Entity(repositoryClass=JwtRefreshTokenRepository::class)
 * @ORM\Table("refresh_tokens")
 */
class JwtRefreshToken extends AbstractRefreshToken
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=128, nullable=true)
     */
    protected $refreshToken;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $username;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $valid;

    public function getId(): ?int
    {
        return $this->id;
    }
}`

and the file config :
gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\JwtRefreshToken

**Comment by mbabker** [comment]
Does your `App\Repository\JwtRefreshTokenRepository` class implement `Gesdinet\JWTRefreshTokenBundle\Doctrine\RefreshTokenRepositoryInterface`?  That's what the check around that error message is looking for.

**Comment by groupemyconnecting** [comment]
@mbabker thank you i have added the impelement
