### ISSUE TITLE
[RFC] 2.0 Proposal

### ISSUE THREAD

**Issue by mbabker** [markitosgv/JWTRefreshTokenBundle#343]
I've been sitting on a branch for a while that has a bunch of proposed changes for a 2.0 branch.  You can see the diff [here](https://github.com/markitosgv/JWTRefreshTokenBundle/compare/master...mbabker:JWTRefreshTokenBundle:2.0-proposal) and the relevant [upgrade guide](https://github.com/mbabker/JWTRefreshTokenBundle/blob/2.0-proposal/UPGRADE-2.0.md).

To sum it up though:
- Minimum supported Symfony version is now 5.4
- Minimum supported PHP version is now 8.1 (the [Packagist stats for the 1.x releases](https://packagist.org/packages/gesdinet/jwt-refresh-token-bundle/php-stats#1) show this covers ~70% of users)
- Deprecated functionality dropped
- Typehints everywhere

So, it's not a huge release as far as major versions go.  But, given Symfony 4.4 is about to stop receiving regular maintenance and go into LTS security-only support, this is a good time to look at what dropping support for it looks like.  As for the PHP minimum, 7.4 reaches its end of support in a couple of months and Symfony 6 uses 8.1 as a minimum, so these versions would match up nicely.  And for those still on older Symfony or PHP versions, the 1.x branch is still there and totally usable.

**Comment by geoffroyp** [comment]
Everything makes sense in my opinion

Go for it! :)

**Comment by thomaspicquet** [comment]
@mbabker great work, would love to see this new 2.0 version started, let me know if you want a beta tester

**Comment by ger86** [comment]
Great @mbabker . Can I help you in accomplishing this update?

**Comment by mbabker** [comment]
PR @ #347
