### ISSUE TITLE
Deprecation warnings with Symfony 5.4 and PHP 8.1

### ISSUE THREAD

**Issue by shakaran** [markitosgv/JWTRefreshTokenBundle#351]
I am using 2.16 of this bundle, and I am getting this warnings:

`
Method "Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()" might add "TreeBuilder" as a native return type declaration in the future. Do the same in implementation "Gesdinet\JWTRefreshTokenBundle\DependencyInjection\Configuration" now to avoid errors or add an explicit @return annotation to suppress this message.`

`Method "Symfony\Component\Console\Command\Command::execute()" might add "int" as a native return type declaration in the future. Do the same in child class "Gesdinet\JWTRefreshTokenBundle\Command\ClearInvalidRefreshTokensCommand" now to avoid errors or add an explicit @return annotation to suppress this message.`

`Method "Symfony\Component\Console\Command\Command::execute()" might add "int" as a native return type declaration in the future. Do the same in child class "Gesdinet\JWTRefreshTokenBundle\Command\RevokeRefreshTokenCommand" now to avoid errors or add an explicit @return annotation to suppress this message.`

I will appreciate a lot, how get rid of them or which is needed to update for avoid it. Thanks

**Comment by acardielwata** [comment]
Same with Symfony 6.3 and gesdinet/jwt-refresh-token-bundle v1.1.1:

![image](https://github.com/markitosgv/JWTRefreshTokenBundle/assets/91546935/aa9e7c1b-943e-477a-a378-862bf0369790)

**Comment by mbabker** [comment]
Fixed with 1.1.2
