### ISSUE TITLE
Logout listener

### ISSUE THREAD

**Issue by HrjSnz** [markitosgv/JWTRefreshTokenBundle#353]
Hello, i noticed, there is logout listener which remove 'refresh_token' from cookies. Ok this is great. But i have question. I would like remove 'BEARER' token too from cookies. Is there way how modify or override this event listener ? 

this is not exception saved, but i would like remove both tokens. When is possible remove refresh_token why would not be possible remove other token too ?
(LogoutEventListener)
![image](https://user-images.githubusercontent.com/81477556/212654735-d8006380-b7ec-4107-bf30-74078e4af772.png)

**Comment by mbabker** [comment]
The logout listener from this bundle is only handling the cookie for the refresh token.  This would be a good feature request for [LexikJWTAuthenticationBundle](https://github.com/lexik/LexikJWTAuthenticationBundle) as that's where the authentication cookie is being created.

**Comment by HrjSnz** [comment]
ok, thanks :) I just registered my logoutListener changed priorty and now it works together. My for remove JWT token and this for remove refresh token
