### ISSUE TITLE
Fatal error on latest version with Symfony 7

### ISSUE THREAD

**Issue by gordinskiy** [markitosgv/JWTRefreshTokenBundle#369]
Updating to Symfony 7+ leads to fatal error:

> Fatal error: Declaration of Gesdinet\JWTRefreshTokenBundle\Security\Exception\InvalidTokenException::getMessageKey() must be compatible with Symfony\Component\Security\Core\Exception\AuthenticationException::getMessageKey(): string in /opt/project/vendor/gesdinet/jwt-refresh-token-bundle/Security/Exception/InvalidTokenException.php on line 21

**gesdinet/jwt-refresh-token-bundle**: v1.2.0
**Symfony/***: v7.0.1

**Comment by mbabker** [comment]
https://github.com/markitosgv/JWTRefreshTokenBundle/pull/366
